/*
-- Query: SELECT * FROM dealership.automobile
LIMIT 0, 1000

-- Date: 2019-05-22 21:26
*/
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('15C5W450145PLA4N4',1989,'Mazda','Miata','compact','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('18487021GK81H4XUB',1997,'Toyota','Corolla','compact','light green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('1C486T6233E1FU6V2',1987,'Kia','Sedona','sedan','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('1E0054A1FUP18G8X9',2007,'Mazda','Miata','compact','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('1RZ3ARDSU2U8S2X8K',2010,'Toyota','4Runner','SUV','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('1UAPTC2M3G9ERZDK1',2002,'Honda','Accord','sedan','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('20113324WTT5TDV84',2011,'Ford','Taurus','sedan','red');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('20HA5HL4L46F5W3SR',2003,'Ford','Focus','compact','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('21150X24K013H1VP6',1986,'Kia','Sedona','sedan','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('2772M3D6W38B0MWC6',1997,'Ford','Focus','compact','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('2S9ZBFPL4L4EVKC6T',1992,'Lexus','ES 350','sedan','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('313WNV4V3M6WFNR0F',2006,'Chevrolet','Impala','sedan','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('3LKWD6S9MY72211AD',1992,'GMC','Yukon','SUV','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('423TK695N6F565242',1990,'GMC','Yukon','SUV','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('42531WA0V671CWEXK',2002,'Chevrolet','Impala','sedan','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('42EVR311535D0LN72',1989,'Honda','Civic','compact','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('44JPM870Y1394T7Z6',2002,'Toyota','Corolla','compact','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('46PRL9PV9G78GMA27',1997,'Ford','Excursion','SUV','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('479XD3KCNA4EJ48PB',2003,'Toyota','Corolla','compact','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('487V7K5XWC61VAKTG',1993,'Mazda','3','coupe','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('4EDHN7BZ8CX39Z9X9',2004,'Mazda','3','coupe','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('4EWV747FSH3V419L3',1988,'Chevrolet','Camaro','coupe','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('4R4A51193B1B1MYDT',2007,'Toyota','Camry','sedan','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('4T4X2JND8ABTWBJ1R',2002,'Toyota','Prius','compact','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('4TT03CC71BW231U49',2013,'GMC','Yukon','SUV','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('4Z56B35S63ML3Z5J8',1988,'Ford','Excursion','SUV','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('511JDUV5CXSPL1R5U',2013,'Ford','Excursion','SUV','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('58V9M2PAFKJSV0N6H',1989,'Mazda','Miata','compact','red');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('5GT71JVJ6A0DRTNUR',2015,'Mazda','Protege','compact','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('5NK27GXW2HV8W10D9',1990,'Lexus','ES 350','sedan','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('5R884SE29V06DXW5W',1995,'BMW','535i','sedan','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('5YT6FXN87XSV70779',2006,'BMW','535i','sedan','light green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('5ZV51H80N1F7G145T',1998,'Toyota','Camry','sedan','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('62DWDDCT04768WK1Y',1993,'Honda','Civic','compact','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('62XWT1KVTJM7H425H',1988,'GMC','Acadia','SUV','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('63DJ3Y2L6757PF0E2',2015,'Mazda','6','sedan','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('63ECH13CJNA6DNRE5',1997,'BMW','535i','sedan','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('654607M7VGNKFZS5N',1999,'Chevrolet','Colorado','SUV','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('687K1CE66CFLRR2P3',1999,'Toyota','Corolla','compact','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('6941N73WAB8L7LY6N',2011,'Mazda','Protege','compact','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('696B48G7512H19NKZ',1992,'Buick','Encore','SUV','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('6B8W62U6R2661F2M0',2009,'Ford','Focus','compact','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('6J55B85RK6E32P7VT',2001,'Toyota','Camry','sedan','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('6L7SXWRY85WX00J1U',1991,'Chevrolet','Colorado','SUV','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('6PKSK08WK79D6FED2',1992,'Honda','Accord','sedan','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('6R0424K27368EFJ6T',1998,'BMW','535i','sedan','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('72473XJ6A5HB04X6Z',2013,'Chevrolet','Colorado','SUV','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('72WG0RZ5EAM400ACB',1996,'Toyota','4Runner','SUV','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('79DY2514M6EE2FD6U',2000,'Chevrolet','Colorado','SUV','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('7EHEL5W8T8M1533C1',2003,'Mazda','3','coupe','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('7G6VB5S7VJS525A3J',1992,'Ford','F150','pickup','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('7TCJNT239ECWG8V02',2005,'Mazda','3','coupe','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('7W2C83140617F3G66',2003,'Toyota','Corolla','compact','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('8338559G1E3269978',1997,'Buick','LeSabre','sedan','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('87N17A49T33GL8X5G',2007,'Mazda','6','sedan','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('8HL7KVZYW5AYJ26TJ',2003,'Kia','Optima','compact','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('8J07ZV4022DJ7KGS7',2007,'Ford','F150','pickup','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('929GTBN45B7K4AL47',2012,'Ford','Excursion','SUV','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('942C93T3DJ24SPBV7',2013,'Toyota','Corolla','compact','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('9K9FHLX688BSM97JF',2002,'GMC','Acadia','SUV','blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('9S2K946XN89355V51',1995,'GMC','Yukon','SUV','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('9W26RP684DT35JJ54',2001,'Ford','Mustang','coupe','red');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('A13K6L88FV072MM1R',1987,'Ford','Excursion','SUV','blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('A7XXX27AME96B7Y0Z',1990,'Mazda','3','coupe','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('AFCNAT9D4JHFL27ER',2009,'Mazda','6','sedan','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('AT3KK408GM88UU0V6',2009,'GMC','Yukon','SUV','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('BZ43CFAK3C5RKF33R',2001,'Kia','Optima','compact','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('C1ME4B0EHN4955DM4',1993,'Lexus','ES 350','sedan','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('C4ZBR087SLFZV9174',2007,'Ford','Taurus','sedan','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('CE13Z4Y87FW9BPEJP',2015,'Ford','Mustang','coupe','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('CGP1B8Z04F56J206P',1987,'Ford','Mustang','coupe','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('CMA7UA5ADCHP23CAF',1997,'Chevrolet','Camaro','coupe','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('DJX856PR17HL83FPS',1995,'Ford','F150','pickup','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('E64MDJMYMKMN5TNAM',2015,'Ford','Focus','compact','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('EGTR67Z82H48CMM9U',1995,'Lexus','ES 350','sedan','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('F1F4R189CYMSVEU0N',2002,'GMC','Yukon','SUV','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('F829362X5JN985S5A',2005,'BMW','535i','sedan','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('FA8627G82RPY42XWG',1993,'Ford','Focus','compact','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('FF0F07Z3RLUTLK607',2000,'Toyota','Prius','compact','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('FTH68X0RTGUB136GZ',1989,'Honda','Civic','compact','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('FUXFHZNK5K52XVYY7',1993,'GMC','Acadia','SUV','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('G377HF85MY2P41940',2006,'Ford','Taurus','sedan','red');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('G4B560EJ9CMRCSZKU',1993,'GMC','Yukon','SUV','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('G5E2W2XR69427MR2U',1996,'Ford','Focus','compact','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('G924XTF2KJWFKB1RA',2010,'GMC','Acadia','SUV','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('GZJ7KB68ZL6G2630D',1989,'Chevrolet','Camaro','coupe','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('J0GF3X73V93GZD6DL',1998,'Ford','Mustang','coupe','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('J4H988P0Z2ZL06623',2015,'Chevrolet','Colorado','SUV','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('J4XAD40XFRE6KBD36',2002,'GMC','Acadia','SUV','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('J885T2RR65UYVAFL2',2005,'Mazda','6','sedan','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('J9219UN6Z6RVA7UJC',1992,'Ford','Focus','compact','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('K53V367G3Z2WJ11RE',1994,'Mercury','Cougar','coupe','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('K7J7Y85K9C9571R0X',2006,'Toyota','4Runner','SUV','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('K99L90JVEZJLJ2486',1989,'Ford','Focus','compact','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('KHAJPACU8X48WE1A3',2011,'Mazda','Protege','compact','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('LJF1A578BD39XJ9FF',2008,'Toyota','Camry','sedan','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('LS3CJ20B3K9UVRHV6',1989,'GMC','Yukon','SUV','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('M0B0URY1A275HT3N6',1996,'Chevrolet','Colorado','SUV','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('M39579R49U10X88D2',2013,'Buick','LeSabre','sedan','blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('MH1B78EP06BFS29YK',1987,'Buick','Encore','SUV','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('N0M06EL87680X9G56',2015,'Mazda','Miata','compact','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('N107GPWM6SZ7G25K6',1993,'Ford','Focus','compact','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('N11KYCU190ZR1JRFE',2009,'Ford','Taurus','sedan','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('N9Y4VPJ0JAR3062TZ',1997,'Kia','Sephia','sedan','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('NAUHLU0HX1PK4U812',1997,'Toyota','4Runner','SUV','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('NDU60S990WV6KD4M8',2008,'Chevrolet','Corvette','coupe','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('NMTVZ3BLD19KN38YA',1999,'Lexus','ES 350','sedan','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('P36888YNRP74KY23Z',1997,'Buick','LeSabre','sedan','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('P57L631AFB651HCH5',2001,'Lexus','ES 350','sedan','red');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('P8NYS017KWN046F37',1987,'Mazda','3','coupe','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('PFACC8UPDW9T24222',2015,'Chevrolet','Camaro','coupe','red');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('R19T9X51YEK3UH04R',1998,'BMW','535i','sedan','blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('RD4W18R2C8N7N8X10',2000,'Chevrolet','Colorado','SUV','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('SE829H4TWLB2EPGU6',2004,'Chevrolet','Camaro','coupe','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('SY7MVJF2JS4G5HGY6',2005,'Mazda','6','sedan','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('T2A68T212JEVG49M3',1997,'Honda','Accord','sedan','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('T2X1013A26Y589P3D',2001,'Kia','Optima','compact','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('TTY9FXCV51FXDY04U',2012,'GMC','Yukon','SUV','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('U1547SH05P9CGV026',1996,'Mazda','Miata','compact','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('U16ZRNE3ZHFLK50G6',2003,'Honda','Accord','sedan','silver');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('U53U5BUU0HGHZ5TG0',2005,'GMC','Yukon','SUV','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('U60YK243S54PRY40K',2000,'Kia','Sedona','sedan','green');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('UCZB03A8TS8CEV5JG',1987,'Toyota','Prius','compact','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('ULV23JCTA1K9J3V19',1993,'Chevrolet','Colorado','SUV','gold');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('UVR2ALD9L9U1AAMFJ',2011,'Mazda','Protege','compact','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('V2GK86F03KD06VVAE',2003,'Mazda','3','coupe','maroon');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('V6597518UZRVGCFS3',1997,'GMC','Yukon','SUV','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('VVX2Y0B070P2TS5C7',2007,'Mercury','Cougar','coupe','red');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('WET81044RPP8ZFZ34',2000,'Mazda','3','coupe','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('WFL53H248XP1P4T6F',1988,'Chevrolet','Colorado','SUV','blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('WGKC20KHX4S5SF6TH',1999,'Toyota','Camry','sedan','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('WX508RGS6B27E37XN',2015,'Mazda','Miata','compact','yellow');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('X12U48E6V4TPJ8R8Z',2002,'Mazda','Miata','compact','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('X5Z2B257SJA3E5E1W',1996,'Mazda','3','coupe','teal');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('XTC7MFXXNCJ46LW82',1992,'Mercury','Cougar','coupe','orange');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('XW22UXN5J40927T19',2006,'Kia','Optima','compact','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('Y62901939Y63X6H0J',1988,'Kia','Optima','compact','light blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('Z0PXGK89564B4GV69',2013,'Chevrolet','Camaro','coupe','blue');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('Z76VZ87E3558179GM',1994,'Kia','Sephia','sedan','white');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('ZDV39LLZ77CZ580CH',1993,'Ford','F150','pickup','black');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('ZLNMK28H3X7FJBT0G',2015,'Toyota','Corolla','compact','cream');
INSERT INTO `automobile` (`VIN`,`year`,`make`,`model`,`body`,`color`) VALUES ('ZX4MBRNPBGN0YK9AS',1989,'Chevrolet','Impala','sedan','black');
